<?php
$labels = array();
$labels['pluginname'] = 'حسابات IMAP الخارجية';
$labels['plugindescription'] = 'ربط خوادم IMAP بهويات الحسابات على مستوى كل مستخدم.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'ممكّنة';
$labels['imapserver'] = 'خادم IMAP';
$labels['imapuser'] = 'اسم المستخدم';
$labels['imappass'] = 'كلمة المرور';
$labels['delimiter'] = 'محدد التسلسل الهرمي للمجلد';
$labels['dot'] = 'نقطة';
$labels['slash'] = 'القطع';
$labels['backslash'] = 'شرطة مائلة للخلف';
$labels['label'] = 'التسمية';
$labels['isset'] = 'كلمة المرور المحفوظة بالفعل';
$labels['isnotset'] = 'الرجاء إدخال كلمة المرور';
$labels['browsingremoteaccount'] = 'باستخدام الحساب البعيد ~';
$labels['connectionfailed'] = 'فشل إنشاء اتصال بخادم IMAP.';
$labels['googlecaptchahint'] = 'أنت تضيف حساب Google إلى بريد الويب الخاص بك. لقد حظرت Google الطلب. يرجى التحقق من تفاصيل حسابك (اسم المستخدم/كلمة المرور). إذا كنت مقتنعًا بالتأكيد أن بيانات الاعتماد الخاصة بك صحيحة، يرجى النقر على %s واتباع تعليمات Google لتمكين الوصول إلى بريد الويب إلى حسابك على Google.';
$labels['here'] = 'هنا';
$labels['ie'] = 'أي:';
?>
