<?php
$labels = array();
$labels['pluginname'] = 'Външни акаунти IMAP';
$labels['plugindescription'] = 'Свързване на IMAP сървъри с идентичностите на акаунти на ниво потребител.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Разрешено';
$labels['imapserver'] = 'Сървър IMAP';
$labels['imapuser'] = 'Потребителско име';
$labels['imappass'] = 'Парола';
$labels['delimiter'] = 'Разграничител на йерархията на папките';
$labels['dot'] = 'точка';
$labels['slash'] = 'слъч';
$labels['backslash'] = 'обратна наклонена черта';
$labels['label'] = 'Етикет';
$labels['isset'] = 'Паролата вече е записана';
$labels['isnotset'] = 'Моля, въведете парола';
$labels['browsingremoteaccount'] = 'ИЗПОЛЗВАНЕ НА ОТДАЛЕЧЕН АКАУНТ ~';
$labels['connectionfailed'] = 'Не успя да установи връзка със сървъра IMAP.';
$labels['googlecaptchahint'] = 'Добавяте акаунт в Google към уеб пощата си. Google е блокирала заявката. Моля, проверете данните за профила си (потребителско име/парола). Ако със сигурност сте убедени, че данните ви са верни, моля, щракнете върху %s и следвайте инструкциите на Google, за да разрешите достъпа до Webmail към вашия акаунт в Google.';
$labels['here'] = 'тук';
$labels['ie'] = 'т.е.:';
?>
