// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='Externí IMAPové účty';
$labels['plugindescription']='Umožní přiřadit další externí IMAPové účty k danému lokálnímu účtu.';
$labels['imap']='IMAP';
$labels['enabled']='Povolen (výchozí)';
$labels['imapserver']='IMAP server';
$labels['imapuser']='Uživatelské jméno';
$labels['imappass']='Heslo';
$labels['delimiter']='Oddělovač složek';
$labels['dot']='tečka';
$labels['slash']='lomítko';
$labels['backslash']='zpětné lomítko';
$labels['label']='Popisek';
$labels['isset']='Heslo je již uloženo';
$labels['isnotset']='Zadejte prosím heslo';
$labels['browsingremoteaccount']='PROCHÁZET VZDÁLENÝ ÚČET ~ ';
$labels['connectionfailed']='Nepodařilo se navázat připojení k IMAP serveru.';
$labels['googlecaptchahint']='Přidáváte-li účet Google do svého webmailu a Google zablokuje vaši žádost, tak si prosím zkontrolujte své údaje (uživatelské jméno/heslo). Pokud jste přesvědčeni, že vaše přihlašovací údaje jsou správné, klikněte prosím %s a postupujte podle pokynů společnosti Google tak abyste získali přístup z webmailu k vašemu Google účtu.';
$labels['here']='zde';
$labels['fe']='např.';