<?php
$labels = array();
$labels['pluginname'] = 'Externí účty IMAP';
$labels['plugindescription'] = 'Přiřazení serverů IMAP k identitám účtů na úrovni jednotlivých uživatelů.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Povoleno';
$labels['imapserver'] = 'Server IMAP';
$labels['imapuser'] = 'Uživatelské jméno';
$labels['imappass'] = 'Heslo';
$labels['delimiter'] = 'Oddělovač hierarchie složek';
$labels['dot'] = 'tečka';
$labels['slash'] = 'slash';
$labels['backslash'] = 'zpětné lomítko';
$labels['label'] = 'Štítek';
$labels['isset'] = 'Heslo je již uloženo';
$labels['isnotset'] = 'Zadejte prosím heslo';
$labels['browsingremoteaccount'] = 'POMOCÍ VZDÁLENÉHO ÚČTU ~';
$labels['connectionfailed'] = 'Nepodařilo se navázat spojení se serverem IMAP.';
$labels['googlecaptchahint'] = 'Přidáváte účet Google do své webové pošty. Společnost Google požadavek zablokovala. Zkontrolujte prosím údaje o svém účtu (uživatelské jméno/heslo). Pokud jste určitě přesvědčeni, že jsou vaše přihlašovací údaje správné, klikněte na %s a podle pokynů společnosti Google povolte přístup k webové poště k účtu Google.';
$labels['here'] = 'zde';
$labels['ie'] = 'tj:';
?>
