<?php
$labels = array();
$labels['pluginname'] = 'Eksterne IMAP-konti';
$labels['plugindescription'] = 'Tilknyt IMAP-servere til kontoidentiteter på brugerniveau.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Aktiveret';
$labels['imapserver'] = 'IMAP-server';
$labels['imapuser'] = 'Brugernavn';
$labels['imappass'] = 'Adgangskode';
$labels['delimiter'] = 'Afgrænsning af mappehierarki';
$labels['dot'] = 'prik';
$labels['slash'] = 'skråstreg';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etiket';
$labels['isset'] = 'Adgangskode allerede gemt';
$labels['isnotset'] = 'Indtast venligst adgangskode';
$labels['browsingremoteaccount'] = 'VED HJÆLP AF FJERNKONTO ~';
$labels['connectionfailed'] = 'Kunne ikke oprette forbindelse til IMAP-serveren.';
$labels['googlecaptchahint'] = 'Du er ved at tilføje en Google-konto til din webmail. Google har blokeret anmodningen. Tjek venligst dine kontooplysninger (brugernavn/adgangskode). Hvis du er sikker på, at dine oplysninger er korrekte, skal du klikke på %s og følge Googles instruktioner for at aktivere webmail-adgang til din Google-konto.';
$labels['here'] = 'her';
$labels['ie'] = 'dvs:';
?>
