<?php
$labels = array();
$labels['pluginname'] = 'Externe IMAP-Konten';
$labels['plugindescription'] = 'Verknüpfen Sie IMAP-Server mit den Identitäten der Konten auf Benutzerebene.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Aktiviert';
$labels['imapserver'] = 'IMAP-Server';
$labels['imapuser'] = 'Benutzername';
$labels['imappass'] = 'Passwort';
$labels['delimiter'] = 'Begrenzer der Ordnerhierarchie';
$labels['dot'] = 'punkt';
$labels['slash'] = 'schrägstrich';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etikett';
$labels['isset'] = 'Passwort bereits gespeichert';
$labels['isnotset'] = 'Bitte Passwort eingeben';
$labels['browsingremoteaccount'] = 'MIT ENTFERNTEM KONTO ~';
$labels['connectionfailed'] = 'Es konnte keine Verbindung zum IMAP-Server hergestellt werden.';
$labels['googlecaptchahint'] = 'Sie fügen ein Google-Konto zu Ihrem Webmail hinzu. Google hat die Anfrage blockiert. Bitte überprüfen Sie Ihre Kontodaten (Nutzername/Passwort). Wenn Sie sicher sind, dass Ihre Anmeldedaten korrekt sind, klicken Sie bitte auf %s und folgen Sie den Anweisungen von Google, um den Webmail-Zugang zu Ihrem Google-Konto zu aktivieren.';
$labels['here'] = 'hier';
$labels['ie'] = 'd.h.:';
?>
