// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='Externe IMAP Konten';
$labels['plugindescription']='Jeder Identität einen entsprechenden IMAP-Server auf Benutzerebene zuordnen.';
$labels['imap']='IMAP';
$labels['enabled']='Aktiviert';
$labels['imapserver']='IMAP-Server';
$labels['imapuser']='Benutzername';
$labels['imappass']='Passwort';
$labels['delimiter']='Hierarchietrennzeichen (IMAP-Ordner)';
$labels['dot']='Punkt';
$labels['slash']='Slash';
$labels['backslash']='Backslash';
$labels['label']='Bezeichnung';
$labels['isset']='Passwort ist gespeichert';
$labels['isnotset']='Passwort eingeben';
$labels['browsingremoteaccount']='POSTFACH ~ ';
$labels['connectionfailed']='Verbindung zum IMAP-Server konnte nicht hergestellt werden.';
$labels['googlecaptchahint']='Google hat die Anfrage blockiert. Bitte überprüfen Sie die Zugangsdaten (Benutername/Passwort). Wenn diese richtig sind, dann klicken Sie %s und folgen Sie den weiteren Anweisungen.';
$labels['here']='hier';
$labels['fe']='z.B.:';