<?php
$labels = array();
$labels['pluginname'] = 'Εξωτερικοί λογαριασμοί IMAP';
$labels['plugindescription'] = 'Συνδέστε διακομιστές IMAP με τις ταυτότητες λογαριασμού σε επίπεδο χρήστη.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Ενεργοποιημένο';
$labels['imapserver'] = 'Διακομιστής IMAP';
$labels['imapuser'] = 'Όνομα χρήστη';
$labels['imappass'] = 'Κωδικός πρόσβασης';
$labels['delimiter'] = 'Οριοθέτης ιεραρχίας φακέλων';
$labels['dot'] = 'dot';
$labels['slash'] = 'slash';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Ετικέτα';
$labels['isset'] = 'Ο κωδικός πρόσβασης έχει ήδη αποθηκευτεί';
$labels['isnotset'] = 'Παρακαλώ εισάγετε τον κωδικό πρόσβασης';
$labels['browsingremoteaccount'] = 'ΧΡΗΣΙΜΟΠΟΙΏΝΤΑΣ ΑΠΟΜΑΚΡΥΣΜΈΝΟ ΛΟΓΑΡΙΑΣΜΌ ~';
$labels['connectionfailed'] = 'Απέτυχε η δημιουργία σύνδεσης με το διακομιστή IMAP.';
$labels['googlecaptchahint'] = 'Προσθέτετε έναν λογαριασμό Google στο Webmail σας. Η Google έχει μπλοκάρει το αίτημα. Ελέγξτε τα στοιχεία του λογαριασμού σας (όνομα χρήστη/κωδικός πρόσβασης). Εάν είστε βέβαιοι ότι τα διαπιστευτήριά σας είναι σωστά, κάντε κλικ στο %s και ακολουθήστε τις οδηγίες της Google για να ενεργοποιήσετε την πρόσβαση του webmail στο λογαριασμό σας Google.';
$labels['here'] = 'εδώ';
$labels['ie'] = 'δηλ:';
?>
