// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='External IMAP Accounts';
$labels['plugindescription']='Associate IMAP servers to account\'s identities on a per user level.';
$labels['imap']='IMAP';
$labels['enabled']='Enabled';
$labels['imapserver']='IMAP server';
$labels['imapuser']='Username';
$labels['imappass']='Password';
$labels['delimiter']='Folder hierarchy delimiter';
$labels['dot']='dot';
$labels['slash']='slash';
$labels['backslash']='backslash';
$labels['label']='Label';
$labels['isset']='Password already saved';
$labels['isnotset']='Please enter Password';
$labels['browsingremoteaccount']='USING REMOTE ACCOUNT ~ ';
$labels['connectionfailed']='Failed to establish a connection to IMAP server.';
$labels['googlecaptchahint']='You are adding a Google account to your Webmail. Google has blocked the request. Please check your account details (username/password). If you certainly convinced that your credentials are correct, please click %s and follow Google\'s instructions to enable webmail access to your Google account.';
$labels['here']='here';
$labels['ie']='i.e.:';