<?php
$labels = array();
$labels['pluginname'] = 'Cuentas IMAP externas';
$labels['plugindescription'] = 'Asociar servidores IMAP a identidades de cuenta a nivel de usuario.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Activado';
$labels['imapserver'] = 'Servidor IMAP';
$labels['imapuser'] = 'Nombre de usuario';
$labels['imappass'] = 'Contraseña';
$labels['delimiter'] = 'Delimitador de jerarquía de carpetas';
$labels['dot'] = 'punto';
$labels['slash'] = 'barra';
$labels['backslash'] = 'barra diagonal inversa';
$labels['label'] = 'Etiqueta';
$labels['isset'] = 'Contraseña ya guardada';
$labels['isnotset'] = 'Introduzca la contraseña';
$labels['browsingremoteaccount'] = 'UTILIZANDO LA CUENTA REMOTA ~';
$labels['connectionfailed'] = 'No se ha podido establecer una conexión con el servidor IMAP.';
$labels['googlecaptchahint'] = 'Estás añadiendo una cuenta de Google a tu Webmail. Google ha bloqueado la solicitud. Comprueba los datos de tu cuenta (nombre de usuario/contraseña). Si estás convencido de que tus credenciales son correctas, haz clic en %s y sigue las instrucciones de Google para habilitar el acceso de webmail a tu cuenta de Google.';
$labels['here'] = 'aquí';
$labels['ie'] = 'es decir:';
?>
