// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='Cuentas IMAP Externas';
$labels['plugindescription']='Asociar servidores IMAP con identidades de cuentas a nivel de usuario.';
$labels['imap']='IMAP';
$labels['enabled']='Habilitado';
$labels['imapserver']='Servidor IMAP';
$labels['imapuser']='Nombre de usuario';
$labels['imappass']='Contraseña';
$labels['delimiter']='Delimitador de jerarquía de carpetas';
$labels['dot']='punto';
$labels['slash']='barra diagonal';
$labels['backslash']='barra diagonal inversa';
$labels['label']='Etiqueta';
$labels['isset']='Contraseña ya salvada';
$labels['isnotset']='Por favor, introduzca su contraseña';
$labels['browsingremoteaccount']='NAVEGANDO CUENTA REMOTA ~ ';
$labels['connectionfailed']='No se pudo establecer conexión con el servidor IMAP.';
$labels['googlecaptchahint']='Está agregando una cuenta de Google a su Webmail. Google ha bloqueado la solicitud. Se recomienda revisar los detalles de la cuenta (nombre de usuario/contraseña). Si ciertamente está convencido de que sus credenciales son correctas, por favor haga clic %s y siga las instrucciones de Google...';
$labels['here']='aquí';
$labels['fe']='p.ej.:';