<?php
$labels = array();
$labels['pluginname'] = 'Välised IMAP-kontod';
$labels['plugindescription'] = 'Ühendage IMAP-serverid konto identiteediga kasutaja tasandil.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Lubatud';
$labels['imapserver'] = 'IMAP server';
$labels['imapuser'] = 'Kasutajanimi';
$labels['imappass'] = 'Parool';
$labels['delimiter'] = 'Kaustade hierarhia piiritleja';
$labels['dot'] = 'dot';
$labels['slash'] = 'slash';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Silt';
$labels['isset'] = 'Parool on juba salvestatud';
$labels['isnotset'] = 'Palun sisestage salasõna';
$labels['browsingremoteaccount'] = 'KASUTADES KAUGKONTOT ~';
$labels['connectionfailed'] = 'Ei õnnestunud luua ühendust IMAP-serveriga.';
$labels['googlecaptchahint'] = 'Lisate Google\'i konto oma veebipostile. Google on taotluse blokeerinud. Palun kontrollige oma konto andmeid (kasutajanimi/parool). Kui olete kindlasti veendunud, et teie andmed on õiged, siis klõpsake %s ja järgige Google\'i juhiseid, et võimaldada veebipostile juurdepääs teie Google\'i kontole.';
$labels['here'] = 'siin';
$labels['ie'] = 'st:';
?>
