<?php
$labels = array();
$labels['pluginname'] = 'Ulkoiset IMAP-tilit';
$labels['plugindescription'] = 'Yhdistä IMAP-palvelimet tilien identiteetteihin käyttäjäkohtaisesti.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Käytössä';
$labels['imapserver'] = 'IMAP-palvelin';
$labels['imapuser'] = 'Käyttäjätunnus';
$labels['imappass'] = 'Salasana';
$labels['delimiter'] = 'Kansiohierarkian erotin';
$labels['dot'] = 'piste';
$labels['slash'] = 'slash';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Tarra';
$labels['isset'] = 'Salasana on jo tallennettu';
$labels['isnotset'] = 'Anna salasana';
$labels['browsingremoteaccount'] = 'KÄYTTÄMÄLLÄ ETÄTILIÄ ~';
$labels['connectionfailed'] = 'Yhteyttä IMAP-palvelimeen ei onnistuttu muodostamaan.';
$labels['googlecaptchahint'] = 'Olet lisäämässä Google-tiliä Webmailiin. Google on estänyt pyynnön. Tarkista tilisi tiedot (käyttäjätunnus/salasana). Jos olet varmasti vakuuttunut siitä, että tietosi ovat oikein, napsauta %s ja noudata Googlen ohjeita, jotta voit ottaa käyttöön Google-tilisi webmail-yhteyden.';
$labels['here'] = 'täällä';
$labels['ie'] = 'ts:';
?>
