<?php
$labels = array();
$labels['pluginname'] = 'Comptes IMAP externes';
$labels['plugindescription'] = 'Associer les serveurs IMAP aux identités des comptes au niveau de chaque utilisateur.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Activé';
$labels['imapserver'] = 'Serveur IMAP';
$labels['imapuser'] = 'Nom d\'utilisateur';
$labels['imappass'] = 'Mot de passe';
$labels['delimiter'] = 'Délimiteur de hiérarchie de dossiers';
$labels['dot'] = 'point';
$labels['slash'] = 'rétrécissement';
$labels['backslash'] = 'barre oblique inverse';
$labels['label'] = 'Étiquette';
$labels['isset'] = 'Mot de passe déjà enregistré';
$labels['isnotset'] = 'Veuillez saisir votre mot de passe';
$labels['browsingremoteaccount'] = 'UTILISATION DU COMPTE À DISTANCE ~';
$labels['connectionfailed'] = 'Échec de l\'établissement d\'une connexion avec le serveur IMAP.';
$labels['googlecaptchahint'] = 'Vous ajoutez un compte Google à votre Webmail. Google a bloqué la demande. Veuillez vérifier les détails de votre compte (nom d\'utilisateur/mot de passe). Si vous êtes convaincu que vos informations d\'identification sont correctes, cliquez sur %s et suivez les instructions de Google pour activer l\'accès à votre compte Google par le webmail.';
$labels['here'] = 'ici';
$labels['ie'] = 'c\'est-à-dire :';
?>
