// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='Comptes IMAP externes';
$labels['plugindescription']='Associer un serveur IMAP vers une identité de compte par utilisateur';
$labels['imap']='IMAP';
$labels['enabled']='Activé';
$labels['imapserver']='Serveur IMAP';
$labels['imapuser']='Username';
$labels['imappass']='Mot de passe';
$labels['dot']='point';
$labels['slash']='slash';
$labels['backslash']='backslash';
$labels['label']='Label';
$labels['isset']='Mot de passe déjà sauvegardé';
$labels['isnotset']='Veuillez entrer votre mot de passe';
$labels['browsingremoteaccount']='NAVIGUER SUR LE COMPTE DISTANT ~ ';
$labels['connectionfailed']='Echec lors de l\'établissement de la connexion au serveur IMAP';
$labels['googlecaptchahint']='Vous êtes en train d\'ajouter un comtpe Google à votre Webmail. Google a bloqué la demande. Veuillez vérifier vos données (login/mot de passe). Si vous êtes certains que vos informations sont correctes, veuillez cliquer ici %s et suivre les instruction des Google...';
$labels['here']='ici';
$labels['fe']='Par exemple:';