<?php
$labels = array();
$labels['pluginname'] = 'חשבונות IMAP חיצוניים';
$labels['plugindescription'] = 'שייך שרתים IMAP לזהויות החשבון ברמת המשתמש.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'מופעל';
$labels['imapserver'] = 'שרת IMAP';
$labels['imapuser'] = 'שם משתמש';
$labels['imappass'] = 'סיסמה';
$labels['delimiter'] = 'מפריד היררכיית תיקיות';
$labels['dot'] = 'נקודה';
$labels['slash'] = 'סלאש';
$labels['backslash'] = 'קו נטוי אחורי';
$labels['label'] = 'תווית';
$labels['isset'] = 'הסיסמה כבר נשמרה';
$labels['isnotset'] = 'אנא הזן סיסמה';
$labels['browsingremoteaccount'] = 'שימוש בחשבון מרחוק ~';
$labels['connectionfailed'] = 'לא ניתן ליצור חיבור לשרת IMAP.';
$labels['googlecaptchahint'] = 'אתה מוסיף חשבון Google לדואר האלקטרוני שלך. Google חסם את הבקשה. אנא בדוק את פרטי החשבון שלך (שם משתמש/סיסמה). אם אתה בטוח שהפרטים שלך נכונים, לחץ על %s ופעל לפי ההוראות של Google כדי לאפשר לדואר האלקטרוני שלך לגשת לחשבון Google שלך.';
$labels['here'] = 'כאן';
$labels['ie'] = 'כלומר:';
?>
