<?php
$labels = array();
$labels['pluginname'] = 'Külső IMAP-fiókok';
$labels['plugindescription'] = 'Az IMAP-kiszolgálók hozzárendelése a fiókok azonosítóihoz felhasználói szinten.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Engedélyezve';
$labels['imapserver'] = 'IMAP-kiszolgáló';
$labels['imapuser'] = 'Felhasználónév';
$labels['imappass'] = 'Jelszó';
$labels['delimiter'] = 'Mappahierarchia elválasztójel';
$labels['dot'] = 'pont';
$labels['slash'] = 'slash';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Címke';
$labels['isset'] = 'Jelszó már elmentve';
$labels['isnotset'] = 'Kérjük, adja meg a jelszót';
$labels['browsingremoteaccount'] = 'TÁVOLI FIÓK HASZNÁLATÁVAL ~';
$labels['connectionfailed'] = 'Nem sikerült kapcsolatot létesíteni az IMAP-kiszolgálóval.';
$labels['googlecaptchahint'] = 'Ön egy Google-fiókot ad hozzá a webmailjéhez. A Google blokkolta a kérelmet. Kérjük, ellenőrizze fiókjának adatait (felhasználónév/jelszó). Ha biztosan meggyőződött arról, hogy a hitelesítő adatai helyesek, kattintson a %s gombra, és kövesse a Google utasításait, hogy engedélyezze a webmail hozzáférést a Google-fiókjához.';
$labels['here'] = 'itt';
$labels['ie'] = 'azaz:';
?>
