<?php
$labels = array();
$labels['pluginname'] = 'Akun IMAP Eksternal';
$labels['plugindescription'] = 'Mengaitkan server IMAP dengan identitas akun pada tingkat per pengguna.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Diaktifkan';
$labels['imapserver'] = 'Server IMAP';
$labels['imapuser'] = 'Nama pengguna';
$labels['imappass'] = 'Kata sandi';
$labels['delimiter'] = 'Pembatas hierarki folder';
$labels['dot'] = 'titik';
$labels['slash'] = 'garis miring';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Label';
$labels['isset'] = 'Kata sandi sudah disimpan';
$labels['isnotset'] = 'Silakan masukkan Kata Sandi';
$labels['browsingremoteaccount'] = 'MENGGUNAKAN AKUN JARAK JAUH ~';
$labels['connectionfailed'] = 'Gagal membuat sambungan ke server IMAP.';
$labels['googlecaptchahint'] = 'Anda menambahkan akun Google ke Webmail. Google telah memblokir permintaan tersebut. Periksa detail akun Anda (nama pengguna/kata sandi). Jika Anda yakin bahwa kredensial Anda sudah benar, silakan klik %s dan ikuti petunjuk Google untuk mengaktifkan akses webmail ke akun Google Anda.';
$labels['here'] = 'di sini';
$labels['ie'] = 'yaitu:';
?>
