<?php
$labels = array();
$labels['pluginname'] = 'Account IMAP esterni';
$labels['plugindescription'] = 'Associare i server IMAP alle identità degli account a livello di singolo utente.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Abilitato';
$labels['imapserver'] = 'Server IMAP';
$labels['imapuser'] = 'Nome utente';
$labels['imappass'] = 'Password';
$labels['delimiter'] = 'Delimitatore della gerarchia delle cartelle';
$labels['dot'] = 'punto';
$labels['slash'] = 'barra';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etichetta';
$labels['isset'] = 'Password già salvata';
$labels['isnotset'] = 'Inserire la password';
$labels['browsingremoteaccount'] = 'UTILIZZANDO L\'ACCOUNT REMOTO ~';
$labels['connectionfailed'] = 'Impossibile stabilire una connessione al server IMAP.';
$labels['googlecaptchahint'] = 'State aggiungendo un account Google alla vostra Webmail. Google ha bloccato la richiesta. Controllare i dettagli dell\'account (nome utente/password). Se siete convinti che le vostre credenziali siano corrette, fate clic su %s e seguite le istruzioni di Google per abilitare l\'accesso webmail al vostro account Google.';
$labels['here'] = 'qui';
$labels['ie'] = 'cioè:';
?>
