<?php
$labels = array();
$labels['pluginname'] = '外部IMAPアカウント';
$labels['plugindescription'] = 'ユーザーごとに、IMAPサーバーをアカウントのIDに関連付ける。';
$labels['imap'] = 'アイマップ';
$labels['enabled'] = '有効';
$labels['imapserver'] = 'IMAPサーバー';
$labels['imapuser'] = 'ユーザー名';
$labels['imappass'] = 'パスワード';
$labels['delimiter'] = 'フォルダ階層区切り記号';
$labels['dot'] = 'ドット';
$labels['slash'] = 'かっきる';
$labels['backslash'] = 'バックスラッシュ';
$labels['label'] = 'ラベル';
$labels['isset'] = 'パスワードは保存済み';
$labels['isnotset'] = 'パスワードを入力してください';
$labels['browsingremoteaccount'] = 'リモートアカウントを使って';
$labels['connectionfailed'] = 'IMAPサーバーへの接続確立に失敗しました。';
$labels['googlecaptchahint'] = 'ウェブメールにGoogleアカウントを追加しようとしています。Googleがリクエストをブロックしました。アカウントの詳細（ユーザー名/パスワード）を確認してください。認証情報に間違いがなければ、%s をクリックし、Google の指示に従って Google アカウントへの Web メール アクセスを有効にしてください。';
$labels['here'] = 'これ';
$labels['ie'] = 'すなわち：';
?>
