<?php
$labels = array();
$labels['pluginname'] = '외부 IMAP 계정';
$labels['plugindescription'] = '사용자 단위로 IMAP 서버를 계정의 ID에 연결합니다.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = '활성화됨';
$labels['imapserver'] = 'IMAP 서버';
$labels['imapuser'] = '사용자 이름';
$labels['imappass'] = '비밀번호';
$labels['delimiter'] = '폴더 계층 구분 기호';
$labels['dot'] = 'dot';
$labels['slash'] = '슬래시';
$labels['backslash'] = '백슬래시';
$labels['label'] = '라벨';
$labels['isset'] = '이미 저장된 비밀번호';
$labels['isnotset'] = '비밀번호를 입력하세요';
$labels['browsingremoteaccount'] = '원격 계정 사용 ~';
$labels['connectionfailed'] = 'IMAP 서버에 연결하지 못했습니다.';
$labels['googlecaptchahint'] = '웹메일에 Google 계정을 추가하고 있습니다. Google에서 요청을 차단했습니다. 계정 세부 정보(사용자 아이디/비밀번호)를 확인하세요. 자격 증명이 정확하다고 확신하는 경우 %s를 클릭하고 Google의 안내에 따라 Google 계정에 대한 웹메일 액세스를 활성화하세요.';
$labels['here'] = '여기';
$labels['ie'] = '즉.:';
?>
