<?php
$labels = array();
$labels['pluginname'] = 'Išorinės IMAP paskyros';
$labels['plugindescription'] = 'Susieti IMAP serverius su paskyros tapatybėmis kiekvieno naudotojo lygmeniu.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Įjungta';
$labels['imapserver'] = 'IMAP serveris';
$labels['imapuser'] = 'Vartotojo vardas';
$labels['imappass'] = 'Slaptažodis';
$labels['delimiter'] = 'Aplankų hierarchijos riboženklis';
$labels['dot'] = 'taškas';
$labels['slash'] = 'slash';
$labels['backslash'] = 'atgalinis pasvirasis brūkšnys';
$labels['label'] = 'Etiketė';
$labels['isset'] = 'Slaptažodis jau išsaugotas';
$labels['isnotset'] = 'Įveskite slaptažodį';
$labels['browsingremoteaccount'] = 'NAUDOJANT NUOTOLINĘ PASKYRĄ ~';
$labels['connectionfailed'] = 'Nepavyko užmegzti ryšio su IMAP serveriu.';
$labels['googlecaptchahint'] = 'Į savo žiniatinklio paštą įtraukiate "Google" paskyrą. "Google" užblokavo užklausą. Patikrinkite savo paskyros duomenis (vartotojo vardą ir slaptažodį). Jei tikrai esate įsitikinę, kad jūsų duomenys yra teisingi, spustelėkite %s ir vadovaukitės "Google" nurodymais, kad įjungtumėte "Google" paskyros prieigą prie žiniatinklio pašto.';
$labels['here'] = 'čia';
$labels['ie'] = 't. y.:';
?>
