<?php
$labels = array();
$labels['pluginname'] = 'Ārējie IMAP konti';
$labels['plugindescription'] = 'IMAP serveru saistīšana ar konta identitātēm katra lietotāja līmenī.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Ieslēgts';
$labels['imapserver'] = 'IMAP serveris';
$labels['imapuser'] = 'Lietotājvārds';
$labels['imappass'] = 'Parole';
$labels['delimiter'] = 'Mapes hierarhijas norobežotājs';
$labels['dot'] = 'dot';
$labels['slash'] = 'slash';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etiķete';
$labels['isset'] = 'Parole jau saglabāta';
$labels['isnotset'] = 'Lūdzu, ievadiet paroli';
$labels['browsingremoteaccount'] = 'IZMANTOJOT ATTĀLINĀTO KONTU ~';
$labels['connectionfailed'] = 'Neizdevās izveidot savienojumu ar IMAP serveri.';
$labels['googlecaptchahint'] = 'Jūs pievienojat Google kontu savai tīmekļa pastkaņai. Google ir bloķējis pieprasījumu. Lūdzu, pārbaudiet konta informāciju (lietotājvārdu/paroli). Ja esat pārliecināts, ka jūsu akreditācijas dati ir pareizi, lūdzu, noklikšķiniet uz %s un izpildiet Google norādījumus, lai iespējotu tīmekļa pasta piekļuvi savam Google kontam.';
$labels['here'] = 'šeit';
$labels['ie'] = 't.i.:';
?>
