// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='Externe IMAP Accounts';
$labels['plugindescription']='Koppel IMAP servers aan identiteiten per gebruiker.';
$labels['imap']='IMAP';
$labels['enabled']='Ingeschakeld';
$labels['imapserver']='IMAP server';
$labels['imapuser']='Gebruikersnaam';
$labels['imappass']='Wachtwoord';
$labels['delimiter']='Map-structuur scheidingsteken';
$labels['dot']='punt';
$labels['slash']='schuine streep';
$labels['backslash']='backslash';
$labels['label']='Label';
$labels['isset']='Wachtwoord al opgeslagen';
$labels['isnotset']='Vul het wachtwoord in';
$labels['browsingremoteaccount']='GEBRUIKT EXTERN ACCOUNT ~ ';
$labels['connectionfailed']='Verbinding met IMAP server mislukt.';
$labels['googlecaptchahint']='Je voegt een Google account toe aan je webmail. Google heeft het verzoek echter geweigerd. Controleer of de inloggegevens (gebruikersnaam/wachtwoord) kloppen. Als je zeker weet dat het klopt, klik %s en volg Googles instructies om webmailtoegang aan te zetten.';
$labels['here']='hier';
$labels['ie']='bijv.:';
