<?php
$labels = array();
$labels['pluginname'] = 'Externe IMAP-accounts';
$labels['plugindescription'] = 'IMAP-servers koppelen aan accountidentiteiten op gebruikersniveau.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Ingeschakeld';
$labels['imapserver'] = 'IMAP-server';
$labels['imapuser'] = 'Gebruikersnaam';
$labels['imappass'] = 'Wachtwoord';
$labels['delimiter'] = 'Scheidingsteken voor maphiërarchie';
$labels['dot'] = 'punt';
$labels['slash'] = 'schuine streep';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Label';
$labels['isset'] = 'Wachtwoord al opgeslagen';
$labels['isnotset'] = 'Voer wachtwoord in';
$labels['browsingremoteaccount'] = 'ACCOUNT OP AFSTAND GEBRUIKEN ~';
$labels['connectionfailed'] = 'Verbinding met IMAP-server mislukt.';
$labels['googlecaptchahint'] = 'U voegt een Google-account toe aan uw Webmail. Google heeft het verzoek geblokkeerd. Controleer uw accountgegevens (gebruikersnaam/wachtwoord). Als u er zeker van bent dat uw gegevens correct zijn, klikt u op %s en volgt u de instructies van Google om de webmailtoegang tot uw Google-account in te schakelen.';
$labels['here'] = 'hier';
$labels['ie'] = 'dat wil zeggen:';
?>
