<?php
$labels = array();
$labels['pluginname'] = 'Eksterne IMAP-kontoer';
$labels['plugindescription'] = 'Knytt IMAP-servere til kontoidentiteter på brukernivå.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Aktivert';
$labels['imapserver'] = 'IMAP-server';
$labels['imapuser'] = 'Brukernavn';
$labels['imappass'] = 'Passord';
$labels['delimiter'] = 'Skilletegn for mappehierarki';
$labels['dot'] = 'prikk';
$labels['slash'] = 'skråstrek';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etikett';
$labels['isset'] = 'Passordet er allerede lagret';
$labels['isnotset'] = 'Vennligst skriv inn passord';
$labels['browsingremoteaccount'] = 'VED HJELP AV EKSTERN KONTO ~';
$labels['connectionfailed'] = 'Kunne ikke opprette forbindelse til IMAP-serveren.';
$labels['googlecaptchahint'] = 'Du legger til en Google-konto i webmailen din. Google har blokkert forespørselen. Vennligst sjekk kontoopplysningene dine (brukernavn/passord). Hvis du er sikker på at opplysningene dine er korrekte, klikker du på %s og følger Googles instruksjoner for å aktivere webmailtilgang til Google-kontoen din.';
$labels['here'] = 'her';
$labels['ie'] = 'dvs:';
?>
