<?php
$labels = array();
$labels['pluginname'] = 'Zewnętrzne konta IMAP';
$labels['plugindescription'] = 'Powiązanie serwerów IMAP z tożsamościami kont na poziomie użytkownika.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Włączone';
$labels['imapserver'] = 'Serwer IMAP';
$labels['imapuser'] = 'Nazwa użytkownika';
$labels['imappass'] = 'Hasło';
$labels['delimiter'] = 'Ogranicznik hierarchii folderów';
$labels['dot'] = 'kropka';
$labels['slash'] = 'ukośnik';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etykieta';
$labels['isset'] = 'Hasło zostało już zapisane';
$labels['isnotset'] = 'Wprowadź hasło';
$labels['browsingremoteaccount'] = 'PRZY UŻYCIU KONTA ZDALNEGO ~';
$labels['connectionfailed'] = 'Nie udało się nawiązać połączenia z serwerem IMAP.';
$labels['googlecaptchahint'] = 'Dodajesz konto Google do swojej poczty internetowej. Firma Google zablokowała to żądanie. Sprawdź dane swojego konta (nazwa użytkownika/hasło). Jeśli jesteś przekonany, że Twoje dane uwierzytelniające są poprawne, kliknij %s i postępuj zgodnie z instrukcjami Google, aby włączyć dostęp do poczty internetowej na koncie Google.';
$labels['here'] = 'tutaj';
$labels['ie'] = 'tj:';
?>
