// Additional IMAP Plugin Language File

<?php
$labels=array();
$labels['pluginname']='Zewnętrzne konta IMAP';
$labels['plugindescription']='Umożliwa powiązanie ustawień serwerów IMAP z tożsamościami na poziomie użytkownika.';
$labels['imap']='IMAP';
$labels['enabled']='Włączone';
$labels['imapserver']='Serwer IMAP';
$labels['imapuser']='Nazwa użytkownika';
$labels['imappass']='Hasło';
$labels['delimiter']='Separator w hierarchii folderów';
$labels['dot']='kropka';
$labels['slash']='ukośnik';
$labels['backslash']='odwrócony ukośnik';
$labels['label']='Etykieta';
$labels['isset']='Hasło już jest zachowane';
$labels['isnotset']='Proszę podać hasło';
$labels['browsingremoteaccount']='PRZEGLĄDANIE KONTA ZDALNEGO ~ ';
$labels['connectionfailed']='Nawiązanie połączenia z serwerem IMAP nie powiodło się.';
$labels['googlecaptchahint']='Dodajesz konto Google do swojego Webmaila. Google zablokowało żądanie. Sprawdź swoje ustawienia konta (nazwę użytkownika i hasło). Jeśli jesteś przekonany, że Twoje ustawienia są poprawne, kliknij %s i postępuj zgodnie z instrukcją Google, aby włączyć dostęp do swojego konta Google.';
$labels['here']='tutaj';