<?php
$labels = array();
$labels['pluginname'] = 'Contas IMAP externas';
$labels['plugindescription'] = 'Associar servidores IMAP às identidades da conta em um nível por usuário.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Ativado';
$labels['imapserver'] = 'Servidor IMAP';
$labels['imapuser'] = 'Nome de usuário';
$labels['imappass'] = 'Senha';
$labels['delimiter'] = 'Delimitador de hierarquia de pastas';
$labels['dot'] = 'ponto';
$labels['slash'] = 'barra';
$labels['backslash'] = 'barra invertida';
$labels['label'] = 'Rótulo';
$labels['isset'] = 'Senha já salva';
$labels['isnotset'] = 'Digite a senha';
$labels['browsingremoteaccount'] = 'USANDO A CONTA REMOTA ~';
$labels['connectionfailed'] = 'Falha ao estabelecer uma conexão com o servidor IMAP.';
$labels['googlecaptchahint'] = 'Você está adicionando uma conta do Google ao seu Webmail. O Google bloqueou a solicitação. Verifique os detalhes da sua conta (nome de usuário/senha). Se estiver convencido de que suas credenciais estão corretas, clique em %s e siga as instruções do Google para ativar o acesso ao webmail da sua conta do Google.';
$labels['here'] = 'aqui';
$labels['ie'] = 'ou seja:';
?>
