<?php
$labels = array();
$labels['pluginname'] = 'Conturi IMAP externe';
$labels['plugindescription'] = 'Asocierea serverelor IMAP la identitățile conturilor la nivel de utilizator.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Activat';
$labels['imapserver'] = 'Server IMAP';
$labels['imapuser'] = 'Nume utilizator';
$labels['imappass'] = 'Parolă';
$labels['delimiter'] = 'Delimitator al ierarhiei de foldere';
$labels['dot'] = 'punct';
$labels['slash'] = 'tăietură';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etichetă';
$labels['isset'] = 'Parolă deja salvată';
$labels['isnotset'] = 'Vă rugăm să introduceți parola';
$labels['browsingremoteaccount'] = 'UTILIZÂND CONTUL LA DISTANȚĂ ~';
$labels['connectionfailed'] = 'A eșuat stabilirea unei conexiuni la serverul IMAP.';
$labels['googlecaptchahint'] = 'Adăugați un cont Google la Webmail-ul dvs. Google a blocat solicitarea. Vă rugăm să verificați detaliile contului dvs. (nume de utilizator/parolă). Dacă sunteți convins că datele dvs. de identificare sunt corecte, faceți clic pe %s și urmați instrucțiunile Google pentru a activa accesul Webmail la contul dvs. Google.';
$labels['here'] = 'aici';
$labels['ie'] = 'i.e.:';
?>
