<?php
$labels = array();
$labels['pluginname'] = 'Внешние учетные записи IMAP';
$labels['plugindescription'] = 'Привязка серверов IMAP к учетным записям на уровне каждого пользователя.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Включено';
$labels['imapserver'] = 'Сервер IMAP';
$labels['imapuser'] = 'Имя пользователя';
$labels['imappass'] = 'Пароль';
$labels['delimiter'] = 'Разделитель иерархии папок';
$labels['dot'] = 'точка';
$labels['slash'] = 'слэш';
$labels['backslash'] = 'обратная косая черта';
$labels['label'] = 'Этикетка';
$labels['isset'] = 'Пароль уже сохранен';
$labels['isnotset'] = 'Пожалуйста, введите пароль';
$labels['browsingremoteaccount'] = 'ИСПОЛЬЗОВАНИЕ УДАЛЕННОЙ УЧЕТНОЙ ЗАПИСИ ~';
$labels['connectionfailed'] = 'Не удалось установить соединение с сервером IMAP.';
$labels['googlecaptchahint'] = 'Вы добавляете учетную запись Google в свою веб-почту. Google заблокировал этот запрос. Проверьте, пожалуйста, данные вашего аккаунта (имя пользователя/пароль). Если вы уверены, что ваши данные верны, нажмите %s и следуйте инструкциям Google, чтобы включить доступ к веб-почте для вашего аккаунта Google.';
$labels['here'] = 'здесь';
$labels['ie'] = 'т.е:';
?>
