<?php
$labels = array();
$labels['pluginname'] = 'Externé účty IMAP';
$labels['plugindescription'] = 'Priradenie serverov IMAP k identitám účtov na úrovni jednotlivých používateľov.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Povolené';
$labels['imapserver'] = 'Server IMAP';
$labels['imapuser'] = 'Používateľské meno';
$labels['imappass'] = 'Heslo';
$labels['delimiter'] = 'Oddeľovač hierarchie priečinkov';
$labels['dot'] = 'bodka';
$labels['slash'] = 'lomítko';
$labels['backslash'] = 'spätné lomítko';
$labels['label'] = 'Štítok';
$labels['isset'] = 'Heslo je už uložené';
$labels['isnotset'] = 'Zadajte heslo';
$labels['browsingremoteaccount'] = 'POMOCOU VZDIALENÉHO ÚČTU ~';
$labels['connectionfailed'] = 'Nepodarilo sa nadviazať spojenie so serverom IMAP.';
$labels['googlecaptchahint'] = 'Pridávate konto Google do svojej webovej pošty. Spoločnosť Google túto požiadavku zablokovala. Skontrolujte údaje o svojom účte (používateľské meno/heslo). Ak ste určite presvedčení, že sú vaše prihlasovacie údaje správne, kliknite na tlačidlo %s a postupujte podľa pokynov spoločnosti Google, aby ste povolili prístup k webovej pošte k vášmu účtu Google.';
$labels['here'] = 'tu';
$labels['ie'] = 't. j.:';
?>
