<?php
$labels = array();
$labels['pluginname'] = 'Zunanji računi IMAP';
$labels['plugindescription'] = 'Povezovanje strežnikov IMAP z identitetami računov na ravni posameznega uporabnika.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Omogočeno';
$labels['imapserver'] = 'Strežnik IMAP';
$labels['imapuser'] = 'Uporabniško ime';
$labels['imappass'] = 'Geslo';
$labels['delimiter'] = 'Razmejitev hierarhije mape';
$labels['dot'] = 'pika';
$labels['slash'] = 'slash';
$labels['backslash'] = 'povratna poševnica';
$labels['label'] = 'Oznaka';
$labels['isset'] = 'Geslo je že shranjeno';
$labels['isnotset'] = 'Vnesite geslo';
$labels['browsingremoteaccount'] = 'UPORABA ODDALJENEGA RAČUNA ~';
$labels['connectionfailed'] = 'Ni uspelo vzpostaviti povezave s strežnikom IMAP.';
$labels['googlecaptchahint'] = 'V spletno pošto dodajate Googlov račun. Google je zahtevo blokiral. Preverite podatke o svojem računu (uporabniško ime/geslo). Če ste zagotovo prepričani, da so vaši podatki pravilni, kliknite %s in sledite Googlovim navodilom, da omogočite dostop do spletne pošte v računu Google.';
$labels['here'] = 'tukaj';
$labels['ie'] = 't.j.:';
?>
