<?php
$labels = array();
$labels['pluginname'] = 'Externa IMAP-konton';
$labels['plugindescription'] = 'Koppla IMAP-servrar till kontonas identiteter på en nivå per användare.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Aktiverad';
$labels['imapserver'] = 'IMAP-server';
$labels['imapuser'] = 'Användarnamn';
$labels['imappass'] = 'Lösenord';
$labels['delimiter'] = 'Avgränsare för mapphierarki';
$labels['dot'] = 'punkt';
$labels['slash'] = 'snedstreck';
$labels['backslash'] = 'backslash';
$labels['label'] = 'Etikett';
$labels['isset'] = 'Lösenordet är redan sparat';
$labels['isnotset'] = 'Vänligen ange lösenord';
$labels['browsingremoteaccount'] = 'MED HJÄLP AV FJÄRRKONTO ~';
$labels['connectionfailed'] = 'Misslyckades med att upprätta en anslutning till IMAP-servern.';
$labels['googlecaptchahint'] = 'Du vill lägga till ett Google-konto i din webbmail. Google har blockerat begäran. Kontrollera dina kontouppgifter (användarnamn/lösenord). Om du är övertygad om att dina uppgifter är korrekta, klicka på %s och följ Googles instruktioner för att aktivera webbmailåtkomst till ditt Google-konto.';
$labels['here'] = 'här';
$labels['ie'] = 'dvs:';
?>
