<?php
$labels = array();
$labels['pluginname'] = 'Harici IMAP Hesapları';
$labels['plugindescription'] = 'IMAP sunucularını kullanıcı başına bir düzeyde hesap kimlikleriyle ilişkilendirin.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Etkin';
$labels['imapserver'] = 'IMAP sunucusu';
$labels['imapuser'] = 'Kullanıcı Adı';
$labels['imappass'] = 'Şifre';
$labels['delimiter'] = 'Klasör hiyerarşisi sınırlayıcısı';
$labels['dot'] = 'nokta';
$labels['slash'] = 'eğik çizgi';
$labels['backslash'] = 'ters eğik çizgi';
$labels['label'] = 'Etiket';
$labels['isset'] = 'Şifre zaten kaydedilmiş';
$labels['isnotset'] = 'Lütfen Şifre Giriniz';
$labels['browsingremoteaccount'] = 'UZAK HESAP KULLANARAK ~';
$labels['connectionfailed'] = 'IMAP sunucusuyla bağlantı kurulamadı.';
$labels['googlecaptchahint'] = 'Web postanıza bir Google hesabı ekliyorsunuz. Google bu isteği engelledi. Lütfen hesap bilgilerinizi (kullanıcı adı/şifre) kontrol edin. Kimlik bilgilerinizin doğru olduğuna kesinlikle ikna olduysanız, lütfen %s\'ye tıklayın ve Google hesabınıza web posta erişimini etkinleştirmek için Google\'ın talimatlarını izleyin.';
$labels['here'] = 'burada';
$labels['ie'] = 'yani:';
?>
