<?php
$labels = array();
$labels['pluginname'] = 'Зовнішні облікові записи IMAP';
$labels['plugindescription'] = 'Пов\'язуйте IMAP-сервери з ідентифікаторами облікових записів на рівні кожного користувача.';
$labels['imap'] = 'IMAP';
$labels['enabled'] = 'Увімкнено';
$labels['imapserver'] = 'Сервер IMAP';
$labels['imapuser'] = 'Ім\'я користувача';
$labels['imappass'] = 'Пароль';
$labels['delimiter'] = 'Розмежувач ієрархії папок';
$labels['dot'] = 'точка';
$labels['slash'] = 'коса риска';
$labels['backslash'] = 'зворотна коса риска';
$labels['label'] = 'Етикетка';
$labels['isset'] = 'Пароль вже збережено';
$labels['isnotset'] = 'Будь ласка, введіть Пароль';
$labels['browsingremoteaccount'] = 'ЗА ДОПОМОГОЮ ВІДДАЛЕНОГО ОБЛІКОВОГО ЗАПИСУ ~';
$labels['connectionfailed'] = 'Не вдалося встановити з\'єднання з IMAP-сервером.';
$labels['googlecaptchahint'] = 'Ви додаєте обліковий запис Google до своєї веб-пошти. Google заблокував запит. Будь ласка, перевірте дані свого облікового запису (ім\'я користувача/пароль). Якщо ви впевнені, що ваші облікові дані правильні, натисніть %s і дотримуйтесь інструкцій Google, щоб увімкнути доступ до веб-пошти у вашому обліковому записі Google.';
$labels['here'] = 'тут';
$labels['ie'] = 'тобто:';
?>
