<?php
$labels = array();
$labels['pluginname'] = 'Tài khoản IMAP bên ngoài';
$labels['plugindescription'] = 'Kết nối các máy chủ IMAP với các danh tính của tài khoản trên từng người dùng.';
$labels['imap'] = 'Giao thức truy cập thư điện tử IMAP';
$labels['enabled'] = 'Đã bật';
$labels['imapserver'] = 'Máy chủ IMAP';
$labels['imapuser'] = 'Tên đăng nhập';
$labels['imappass'] = 'Mật khẩu';
$labels['delimiter'] = 'Dấu phân cách cấu trúc thư mục';
$labels['dot'] = 'chấm';
$labels['slash'] = 'gạch chéo';
$labels['backslash'] = 'dấu gạch chéo ngược';
$labels['label'] = 'Nhãn';
$labels['isset'] = 'Mật khẩu đã được lưu';
$labels['isnotset'] = 'Vui lòng nhập mật khẩu';
$labels['browsingremoteaccount'] = 'SỬ DỤNG TÀI KHOẢN TỪ XA ~';
$labels['connectionfailed'] = 'Không thể thiết lập kết nối với máy chủ IMAP.';
$labels['googlecaptchahint'] = 'Bạn đang thêm tài khoản Google vào Webmail. Google đã chặn yêu cầu này. Vui lòng kiểm tra thông tin tài khoản của bạn (tên người dùng/mật khẩu). Nếu bạn chắc chắn rằng thông tin đăng nhập của mình là chính xác, vui lòng nhấp vào %s và làm theo hướng dẫn của Google để kích hoạt quyền truy cập Webmail cho tài khoản Google của bạn.';
$labels['here'] = 'đây';
$labels['ie'] = 'ví dụ:';
?>
