<?php
$labels = array();
$labels['pluginname'] = '外部 IMAP 账户';
$labels['plugindescription'] = '按用户级别将 IMAP 服务器与账户身份关联。';
$labels['imap'] = 'IMAP';
$labels['enabled'] = '已启用';
$labels['imapserver'] = 'IMAP 服务器';
$labels['imapuser'] = '用户名';
$labels['imappass'] = '密码';
$labels['delimiter'] = '文件夹层次分隔符';
$labels['dot'] = '点子';
$labels['slash'] = '斜杠';
$labels['backslash'] = '反斜杠';
$labels['label'] = '标签';
$labels['isset'] = '已保存密码';
$labels['isnotset'] = '请输入密码';
$labels['browsingremoteaccount'] = '使用远程帐户 ~';
$labels['connectionfailed'] = '与 IMAP 服务器建立连接失败。';
$labels['googlecaptchahint'] = '您正在向 Webmail 添加 Google 帐户。Google 已阻止该请求。请检查您的帐户详细信息（用户名/密码）。如果您确信您的凭据是正确的，请单击 %s 并按照 Google 的说明启用 Webmail 访问您的 Google 帐户。';
$labels['here'] = '这里';
$labels['ie'] = '即';
?>
